version: '3'

volumes:
  postgres_data:
    driver: local

services:

  keycloak-postgres:
    image: postgres:14
    container_name: keycloak-postgres
 #   volumes:
 #     - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak" ]
      interval: 5s
      timeout: 5s
      retries: 5        
    ports:
      - 5433:5432

  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    container_name: keycloak
    command:
      - start-dev
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB_URL_HOST: keycloak-postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_SCHEMA: public
      KC_HTTP_PORT: 8081
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME_STRICT: 'false'
      KC_HTTP_ENABLED: 'true'
      KC_HEALTH_ENABLED: 'true'
      KC_HOSTNAME_ADMIN: localhost
      KC_HOSTNAME: keycloak
      KC_FEATURES: declarative-user-profile
      KC_SPI_EVENTS_LISTENER_OPENFGA_EVENTS_PUBLISHER_API_URL: http://openfga:8080
      KC_LOG_LEVEL: INFO, com.twogenidentity.keycloak:debug,com.twogenidentity.keycloak.utils:debug
    healthcheck:
      # test: ["CMD", "curl", "-f", "http://localhost:8081/health/ready"]
      test: cat /proc/net/tcp | grep '00000000:1F91 00000000:0000' || exit 1
      interval: 5s
      timeout: 2s
      retries: 15         
    ports:
      - 8081:8081
      - 8443:8443
    volumes:
      - $PWD/keycloak/lib/keycloak-openfga-event-publisher-1.0.0.jar:/opt/keycloak/providers/keycloak-openfga-event-publisher-1.0.0.jar
      - $PWD/keycloak/initialize-poc.sh:/opt/keycloak/initialize-poc.sh
    depends_on:
      - keycloak-postgres